### ISSUE TITLE
Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, 

### ISSUE THREAD

**Issue by sunpasup** [AndyMeps/ng2-dropdown-multiselect#12]
ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in /Users/sunpasup/Documents/workspace/360NEW/mbr-jbosseap6/web/node_modules/ng2-dropdown-multiselect/node_modules/@angular/core/src/metadata/ng_module.d.ts, resolving symbol NgModule in /Users/sunpasup/Documents/workspace/360NEW/mbr-jbosseap6/web/node_modules/ng2-dropdown-multiselect/node_modules/@angular/core/src/metadata.d.ts, resolving symbol NgModule in /Users/sunpasup/Documents/workspace/360NEW/mbr-jbosseap6/web/node_modules/ng2-dropdown-multiselect/node_modules/@angular/core/src/core.d.ts, resolving symbol NgModule in /Users/sunpasup/Documents/workspace/360NEW/mbr-jbosseap6/web/node_modules/ng2-dropdown-multiselect/node_modules/@angular/core/index.d.ts, resolving symbol DropdownMultiselectModule in /Users/sunpasup/Documents/workspace/360NEW/mbr-jbosseap6/web/node_modules/ng2-dropdown-multiselect/src/dropdown-multiselect.module.ts, resolving symbol DropdownMultiselectModule in /Users/sunpasup/Documents/workspace/360NEW/mbr-jbosseap6/web/node_modules/ng2-dropdown-multiselect/src/dropdown-multiselect.module.ts

**This is the Error i am getting with ng2-dropdown-multiselect Please Help me here.**

TIA
<img width="998" alt="screen shot 2017-03-22 at 12 27 04 pm" src="https://cloud.githubusercontent.com/assets/24596204/24216695/6ce18314-0efa-11e7-92d2-398bb623baba.png">

**Comment by sunpasup** [comment]
**after Deleting the Node Modules and Demo Inside node_modules/ng2-dropdown-multiselect its working fine,** 

TIA

**Comment by tmsuresh5** [comment]
Hi,
Let me know what folder  you actually deleted, since am getting the same exception of what you got.
Angular version :2.4.0
Angular-2-dropdown-multiselect:1.0.2

I have deleted the following folders based on your comments, still i get the same exception
C:\Angular2\<Project-Name>\node_modules\ng2-dropdown-multiselect\**demo**
C:\Angular2\first-app\node_modules\ng2-dropdown-multiselect\**node_modules**

**Comment by Ironjanowar** [comment]
I've done the same and I'm getting this error now:

```ERROR in Error encountered resolving symbol values statically. Calling function 'DropdownModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol DropdownMultiselectModule in /home/ironjanowar/project/node_modules/ng2-dropdown-multiselect/src/dropdown-multiselect.module.ts, resolving symbol DropdownMultiselectModule in /home/ironjanowar/project/node_modules/ng2-dropdown-multiselect/src/dropdown-multiselect.module.ts```

**Comment by AndyMeps** [comment]
I get this too, seems to be related to AoT, will look in to resolving this, it's broken my other ng2 libraries too :(

**Comment by WayneBarnard** [comment]
Did anyone manage to get it working again?

**Comment by AndyMeps** [comment]
Hey WayneBarnard, 

I got one of my other libraries up and running again at the weekend, unfortunately I've been ill the past couple of days so haven't been able to fix `ng2-dropdown-multiselect`; I'm working on it slowly, hopefully tonight i'll be able to make some real progress.

Apologies and bear with me,

Cheers,

Andy

**Comment by AndyMeps** [comment]
Fix added in 61d123f - v1.2.0, working with latest versions of angular and ngx-bootstrap.

Closing as duplicate, please comment further in #9
