### ISSUE TITLE
allSelected option not working

### ISSUE THREAD

**Issue by johnnywholesome** [AndyMeps/ng2-dropdown-multiselect#5]
Awesome component..  I'm actually having some trouble getting the allSelected option to work though.  The allSelected: false optoin has no effect.  If I set the value to false, it still displays the dropdown with all of the options checked for some reason.

**Comment by AndyMeps** [comment]
Hi johnnywholesome, 

So sorry I didn't notice this issue! I will look in to this immediately and get back to you. Glad you're finding it useful! :)

Andy

**Comment by AndyMeps** [comment]
Hi johnnywholesome,

You're quite right there was an issue with that config item, I've now committed and published a fix @0.3.2 of ng2-dropdown-multiselect. I hope this helps and thanks for letting me know.

Cheers,

Andy
