### ISSUE TITLE
Cannot read property 'defaultButtonText' of undefined

### ISSUE THREAD

**Issue by dluk** [AndyMeps/ng2-dropdown-multiselect#8]
Following your documentation I get this error in the console:
```
EXCEPTION: Uncaught (in promise): Error: Error in ./HomeComponent class HomeComponent - inline template:9:0 caused by: Cannot read property 'defaultButtonText' of undefined
TypeError: Cannot read property 'defaultButtonText' of undefined
    at DropdownMultiselectComponent.processOptions (http://localhost:8080/app.js:20446:25)
    at DropdownMultiselectComponent.ngOnInit (http://localhost:8080/app.js:20395:14)
    at Wrapper_DropdownMultiselectComponent.ngDoCheck (/DropdownMultiselectModule/DropdownMultiselectComponent/wrapper.ngfactory.js:32:53)
    at CompiledTemplate.proxyViewClass.View_HomeComponent0.detectChangesInternal 
...
```

I used everything exactly like in your example
template: 
```
<dropdown-multiselect
    [(ngModel)]="dropdownModel">
</dropdown-multiselect>
```
component:
```
import { Component, OnInit } from '@angular/core';
import { IDropdownItem } from 'ng2-dropdown-multiselect';

@Component({
    selector: 'app-home',
    templateUrl: './home.component.html',
    styleUrls: [
        './home.component.css'
    ]
})
export class HomeComponent implements OnInit {
    public dropdownModel: IDropdownItem[];
    
    ngOnInit() {
        this.dropdownModel = [
        {
            id: 1,
            label: 'Today',
            selected: false, // optional
            color: '#336699' // optional
        }
        // ...
    ];
    }
}
```
module:
```import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';

import { HomeRoutingModule } from './home-routing.module';
import { HomeComponent } from './home.component';
import { DropdownMultiselectModule } from 'ng2-dropdown-multiselect';

@NgModule({
    declarations: [
        HomeComponent
    ],
    imports: [
        HomeRoutingModule,  DropdownMultiselectModule, FormsModule  
    ],
    exports: [
        HomeComponent
    ]
})
export class HomeModule {
}
```
I am using a fresh [angular2-webpack-starter](https://github.com/antonybudianto/angular-webpack-starter)

**Comment by AndyMeps** [comment]
Hi dluk,

Sorry to hear you're having issues, i'll try to recreate and get back to you.

Regards,

Andy

**Comment by AndyMeps** [comment]
Hi dluk,

I'm struggling to recreate this issue, I know this was an issue previously (see #4). What version are you using? v1.0.0 is the latest.

Regards,

Andy

**Comment by dluk** [comment]
Hi again,

Sorry, but I cannot even try to reproduce it because npm install fails when I add the v1.0.0. I get the error installing ng2-bootstrap 1.1.15 and I'm not alone facing this issue https://github.com/npm/npm/issues/15248
Though suggested workarounds from the referenced issue doesn't work for me.
When I remove the ng2-dropdown-multiselect package from package.json then npm install works.
Don't know if you can do anything about it.

**Comment by AndyMeps** [comment]
Hi dluk, 

Thanks for getting back to me. I'll look in to upgrading the library to the latest version of ng2-bootstrap tomorrow to see if this helps.  As a work around using the old version of ng2-dropdown-multiselect (I'm guessing this works for you?), if you add defaultButtonText to your configuration object with the default value (found in documentation) then it should work (untested). 

Hope this helps for the time being, will aim to get something updated tomorrow. 

Regards, 

Andy

**Comment by AndyMeps** [comment]
Hi dluk,

Sorry for the delay, busy time of year! I've migrated the library to support the latest version of ng2-bootstrap and angular 2.

I hope this resolves this issue, will leave this open for 7 days for feedback.

Regards,

Andy

**Comment by thehashrocket** [comment]
Hey, @AndyMeps , just letting you know that I can replicate the issue as well. I'm using:
`"ng2-dropdown-multiselect": "^1.1.0",`
`"ng2-bootstrap": "^1.1.16",`

and getting the same error. 

I've replicated @dluk 's example code and hitting the same wall they are. I'm using `Angular 2.4.0` with `Angular-CLI 1.0.0-beta.24`

**Comment by AndyMeps** [comment]
Hi thehashrocket,

I'll look in to this tonight. Out of curiousity, are you providing an IMultiselectConfig object to the control? Might be worth adding it if you're not and providing defaultButtonText. (See [This Section of the README](https://github.com/AndyMeps/ng2-dropdown-multiselect#configuration))

**Comment by thehashrocket** [comment]
No, my component is super bare bones:

```
import { Component, OnInit } from '@angular/core';
import { IDropdownItem } from 'ng2-dropdown-multiselect';

@Component({
  selector: 'app-activity-home',
  templateUrl: './activity-home.component.html',
  styleUrls: ['./activity-home.component.css']
})
export class ActivityHomeComponent implements OnInit {

  public dropdownModel: IDropdownItem[];

  constructor() { }

  ngOnInit() {
    this.dropdownModel = [
      {
        id: 1,
        label: 'Today',
        selected: false, // optional
        color: '#336699' // optional
      },
      {
        id: 2,
        label: 'Tomorrow',
        selected: false, // optional
        color: '#336699' // optional
      }
      ];
  }

}
```

And in the view it is/was simply:

```
<dropdown-multiselect
    [(ngModel)]="dropdownModel">
</dropdown-multiselect>
```

**Comment by AndyMeps** [comment]
Hi thehashrocket,

In that case I would do the following based on your example until I can get a new patch version to you:

```javascript
import { Component, OnInit } from '@angular/core';
import { IDropdownItem, IMultiselectConfig } from 'ng2-dropdown-multiselect';

@Component({
  selector: 'app-activity-home',
  templateUrl: './activity-home.component.html',
  styleUrls: ['./activity-home.component.css']
})
export class ActivityHomeComponent implements OnInit {

  public dropdownModel: IDropdownItem[];
  public dropdownConfig: IMultiselectConfig;

  constructor() { }

  ngOnInit() {
    this.dropdownModel = [
      {
        id: 1,
        label: 'Today',
        selected: false, // optional
        color: '#336699' // optional
      },
      {
        id: 2,
        label: 'Tomorrow',
        selected: false, // optional
        color: '#336699' // optional
      }
    ];

    this.dropdownConfig = {};
  }

}
```

```html
<dropdown-multiselect
    [(ngModel)]="dropdownModel"
    [dropdownConfig]="dropdownConfig">
</dropdown-multiselect>
```

Hope this helps,

Andy

**Comment by thehashrocket** [comment]
Thanks, I'll give that a shot in a few minutes. Trying to get angular-cli and ng2-bootstrap to play niceley together again. Seems something has changed with AoT or something and they are having issues. . .

**Comment by thehashrocket** [comment]
Sooo, I ran into a different issue, but i'll make a separate ticket for that one since it's unrelated to this. It's just more fun chasing Angular2 changes. lol.

**Comment by AndyMeps** [comment]
No problem, did the fix I suggested resolve the `'defaultButtonText' of undefined` then?

Cheers,

Andy

**Comment by thehashrocket** [comment]
I couldn't test it thanks to the latest issue i ran into. :(

**Comment by hicham-zreik** [comment]
Hi @AndyMeps ,
It works good in all features but I have a problem, I can change css of component but I can't change the css of "multiselect-container " and button . Any Help ?
Thank you in advance.
